DROP DATABASE IF EXISTS IMPRESORA;
CREATE DATABASE IMPRESORA;
USE IMPRESORA;

CREATE TABLE CONTADOR(
    ID INT PRIMARY KEY AUTO_INCREMENT,
    numero INT NOT NULL
);

INSERT INTO contador(numero) VALUES (0);

SELECT * FROM CONTADOR;